### PR TITLE
added possibility to set entropy length

### PR DESCRIPTION
**Pull request by turcane**
So it becomes possible to use shorter or longer mnemonics.

### CODE REVIEW

**Review by keeshux — CHANGES_REQUESTED** [review]
It's all fine, but `generateRandomMnemonic:` should really be `generateRandomMnemonicWithEntropyLength:` in Objective-C.

**Comment by turcane** [comment]
like this?

**Comment by keeshux** [comment]
Heh, nope.

`WSSeedGenerator.h` line 36.
`WSSeedGenerator.m` line 98.

**Comment by turcane** [comment]
Sorry, I really don't know what you mean.

**Comment by keeshux** [comment]
Manually added to master in https://github.com/keeshux/BitcoinSPV/commit/ba933ea4debf28948b613d189454fe70d2bea53d, have a look. Thanks for the addition!

**Pull request closed without merging**
